name: Flutter CI

on:
  push:
    tags:
      - '*' # listen to all tags

jobs:
  build-and-release-linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64
      - name: Install dependencies
        run: sudo apt-get install -y ninja-build libgtk-3-dev liblzma-dev
      - name: Install project dependencies
        run: flutter pub get
      - name: Enable linux build
        run: flutter config --enable-linux-desktop
      - name: Build artifacts
        run: flutter build linux --release
      - name: Archive Release
        uses: thedoctor0/zip-release@master
        with:
          type: 'zip'
          filename: PhenoUI-tester-${{github.ref_name}}-linux.zip
          directory: build/linux/x64/release/bundle
      - name: Linux Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/linux/x64/release/bundle/PhenoUI-tester-${{github.ref_name}}-linux.zip
          overwrite: true

  build-and-release-windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - name: Install project dependencies
        run: flutter pub get
      - name: Enable windows build
        run: flutter config --enable-windows-desktop
      - name: Build artifacts
        run: flutter build windows --release
      - name: Archive Release
        uses: thedoctor0/zip-release@master
        with:
          type: 'zip'
          filename: PhenoUI-tester-${{github.ref_name}}-windows.zip
          directory: build/windows/x64/runner/Release
      - name: Windows Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/windows/x64/runner/Release/PhenoUI-tester-${{github.ref_name}}-windows.zip
          overwrite: true

  build-and-release-macos:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64
      - name: Install project dependencies
        run: flutter pub get
      - name: Enable macOS build
        run: flutter config --enable-macos-desktop
      - name: Build artifacts
        run: flutter build macos --release
      - name: Archive Release
        uses: thedoctor0/zip-release@master
        with:
          type: 'zip'
          filename: PhenoUI-tester-${{github.ref_name}}-macos.zip
          directory: build/macos/Build/Products/Release
      - name: macOS Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/macos/Build/Products/Release/PhenoUI-tester-${{github.ref_name}}-macos.zip
          overwrite: true
